### ISSUE TITLE
ERROR: ||[Errno 21] Is a directory

### ISSUE THREAD

**Issue by v3daxt** [jklepsercyber/defender-detectionhistory-parser#2]
More detail
:'/'|| caught in /. Moving on to next file... 1 of 1 DetectionHistory files found were successfully parsed, with output written to "op.txt" in 0.023249847 seconds.

I am getting this error when I try to run the script 
`python3 dhparser.py -f /home/kali/Desktop/0.exe.zip -o op.txt`
even the output file is not generated

**Comment by jklepsercyber** [comment]
Fixed. Please advise if this happens again so I can reopen and investigate further.
